#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.swipe.likemaster                                          # Enter Google Play Store URL.
presskit_download_link                    :                                       # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/my_logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Tinder Autoliker                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Android App to Autolike on Tinder, Bumble, OkCupid & Tantan

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Maroon Labs                             
your_link                                 : https://play.google.com/store/apps/developer?id=Maroon+Labs&hl=en_IN                   
your_city                                 :                              
email_address                             : autoswiperight@gmail.com
facebook_username                         :                                           
instagram_username                        : autoswiperight
twitter_username                          : autoswiperight
github_username                           : autoswiperight
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Swipe Right/Left
    description                           : Like left or like right, your choice.
    fontawesome_icon_name                 : expand
    
  - title                                 : Fast
    description                           : Adjust the swipe speed as per your need.
    fontawesome_icon_name                 : fast-forward

  - title                                 : Multi App Support
    description                           : Supports Tinder, Bumble, OkCupid & Tantan
    fontawesome_icon_name                 : fire

  - title                                 : Unlimited Swipes
    description                           : Unlimited swipes on dating apps.
    fontawesome_icon_name                 : heart

  - title                                 : Date Anyone
    description                           : Swipe profiles in other countries through the Mock Location
    fontawesome_icon_name                 : globe
  
  - title                                 : Stay Protected
    description                           : Limits on swipe so that you don't get banned on dating apps
    fontawesome_icon_name                 : star



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : /assets/header1.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#fe3c72"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#ff5864"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
